telegram:
  api_id: 15787995
  api_hash: "e51a3154d2e0c45e5ed70251d68382de"
  token: "7964758764:AAGuYr8voir-lrOBUim_mj1w2KfY1-7rsgI"
  lang_code: !!str "en"
  max_upload_tasks: 5
  url_validation_regexes:
    - "^http(s)?:\\/\\/.+$"
  allowed_users:  # Multiple users/groups are allowed.
    - id: 7046488481  # User or group ID.
      is_admin: !!bool True
      send_startup_message: !!bool True
      download_media_type: "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -1002410423843  # Group or channel ID.
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
  api:
    upload_video_file: !!bool False
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:  # User, group or channel IDs.
      - 1002410423843
      - -33333333333
    silent: !!bool False
    video_caption:
      include_title: !!bool True
      include_filename: !!bool False
      include_link: !!bool True
      include_size: !!bool True
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
  release_channel: "NIGHTLY"
